GET http://localhost:3000/escapethestudies/courses
################################################################
GET http://localhost:3000/escapethestudies/question?title=Chapter 2: Was ist HTML - The Constructor
################################################################
GET http://localhost:3000/escapethestudies/answers
################################################################
GET http://localhost:3000/escapethestudies/users
################################################################
GET http://localhost:3000/escapethestudies/chapter/2
################################################################
GET http://localhost:3000/escapethestudies/textdata/5
################################################################
GET http://localhost:3000/escapethestudies/questiontype
################################################################
GET http://localhost:3000/escapethestudies/news
################################################################
GET http://localhost:3000/escapethestudies/tag
################################################################
POST http://localhost:3000/escapethestudies/user
Content-Type: application/json

{
    "email": "userin@example.com",
    "username": "User*in"
}
################################################################
GET http://localhost:3000/escapethestudies/story?title=Chapter 2: Was ist HTML - The Constructor
################################################################
GET http://localhost:3000/escapethestudies/lection?title=Chapter 2: Was ist HTML - The Constructor
################################################################
GET http://localhost:3000/escapethestudies/user
Content-Type: application/json

{
    "email": "userin@example.com"
}
################################################################
GET http://localhost:3000/escapethestudies/userChapter/6
################################################################