GET http://localhost:3000/escapethestudies/courses
################################################################
GET http://localhost:3000/escapethestudies/question?title=Chapter 1: Introduction: Environment und Setup
################################################################
GET http://localhost:3000/escapethestudies/answers
################################################################
GET http://localhost:3000/escapethestudies/users
################################################################
GET http://localhost:3000/escapethestudies/chapter/2
################################################################
GET http://localhost:3000/escapethestudies/textdata/5
################################################################
GET http://localhost:3000/escapethestudies/questiontype
################################################################
GET http://localhost:3000/escapethestudies/news
################################################################
GET http://localhost:3000/escapethestudies/tag
################################################################
POST http://localhost:3000/escapethestudies/user
Content-Type: application/json

{
    "email": "user@example.com",
    "username": "user example"
}
################################################################
GET http://localhost:3000/escapethestudies/story?title=Chapter 1: Introduction: Environment und Setup
################################################################
GET http://localhost:3000/escapethestudies/lection?title=Chapter 1: Introduction: Environment und Setup
################################################################
GET http://localhost:3000/escapethestudies/user
Content-Type: application/json

{
    "email": "user@example.com"
}
################################################################